FROM node:10-alpine
WORKDIR /zeus/
RUN apk add --no-cache git \
  && apk add --no-cache openssh \
  && apk add --no-cache tar \
  && apk add --no-cache gzip \
  && apk add --no-cache ca-certificates
RUN npm install -g semantic-release@15

